[package]
name = "starnamics/rongo"
description = "MongoDB Atlas Data API wrapper for connecting Roblox to MongoDB"
version = "2.1.2"
license = "MIT"
realm = "server"
registry = "https://github.com/UpliftGames/wally-index"
exclude = ["**"]
include = ["src", "src/**", "default.project.json", "wally.toml"]